import { Grid } from "@mui/material";
import ToolsWidget from "@/pages/PlayerDash/Overview/widgets/ToolsWidget";
import { TeamData, TeamRoster } from "@/types/Dash/TeamDash";
import TeamExInfo from "@/pages/TeamDash/Overview/widgets/TeamExInfo";  
import RosterWidget from "./widgets/RosterWidget";
interface RosterProps {
  teamData: TeamData;
}



const RosterData:TeamRoster = {
  "statusCode": 200,
  "body": {
    "team": "SAC",
    "teamID": "26",
    "roster": [
      {
        "college": "Alabama",
        "fantasyProsLink": "https://www.fantasypros.com/nba/players/keon-ellis.php",
        "jerseyNum": "23",
        "bRefID": "elliske01",
        "espnName": "Keon Ellis",
        "yahooLink": "https://sports.yahoo.com/nba/players/6753",
        "sleeperBotID": "2432",
        "fantasyProsPlayerID": "5505",
        "nbaComLink": "https://www.nba.com/player/1631165",
        "nbaComHeadshot": "https://cdn.nba.com/headshots/nba/latest/1040x760/1631165.png",
        "lastGamePlayed": "20240107_NO@SAC",
        "espnLink": "https://www.espn.com/nba/player/_/id/4702177/keon-ellis",
        "yahooPlayerID": "6753",
        "pos": "SG",
        "teamID": "26",
        "injury": {
          "description": "",
          "injDate": "",
          "designation": ""
        },
        "nbaComName": "Keon Ellis",
        "rotoWirePlayerIDFull": "keon-ellis-5659",
        "rotoWirePlayerID": "5659",
        "exp": "1",
        "height": "6-3",
        "nbaComID": "1631165",
        "espnHeadshot": "https://a.espncdn.com/combiner/i?img=/i/headshots/nophoto.png&w=200&h=146",
        "espnID": "4702177",
        "weight": "175",
        "team": "SAC",
        "bRefName": "Keon Ellis",
        "espnShortName": "K. Ellis",
        "bDay": "1/8/2000",
        "shortName": "K. Ellis",
        "longName": "Keon Ellis",
        "playerID": "94144465527",
        "stats": {
          "blk": "0.5",
          "fga": "3.2",
          "DefReb": "1.0",
          "ast": "1.4",
          "ftp": "64.7",
          "tptfgp": "38.1",
          "tptfgm": "1.0",
          "trueShootingPercentage": "60.9",
          "stl": "0.6",
          "fgm": "1.4",
          "pts": "4.3",
          "reb": "1.4",
          "fgp": "44.2",
          "effectiveShootingPercentage": "59.7",
          "fta": "0.7",
          "mins": "13.1",
          "gamesPlayed": "24",
          "TOV": "0.5",
          "tptfga": "2.6",
          "OffReb": "0.4",
          "ftm": "0.5"
        }
      },
      {
        "college": "Kentucky",
        "fantasyProsLink": "https://www.fantasypros.com/nba/players/malik-monk.php",
        "jerseyNum": "0",
        "bRefID": "monkma01",
        "espnName": "Malik Monk",
        "yahooLink": "https://sports.yahoo.com/nba/players/5824",
        "sleeperBotID": "1779",
        "fantasyProsPlayerID": "3313",
        "nbaComLink": "https://www.nba.com/player/1628370",
        "nbaComHeadshot": "https://cdn.nba.com/headshots/nba/latest/1040x760/1628370.png",
        "lastGamePlayed": "20240107_NO@SAC",
        "espnLink": "https://www.espn.com/nba/player/_/id/4066262/malik-monk",
        "yahooPlayerID": "5824",
        "pos": "SG",
        "teamID": "26",
        "injury": {
          "description": "",
          "injDate": "",
          "designation": ""
        },
        "nbaComName": "Malik Monk",
        "rotoWirePlayerIDFull": "malik-monk-4117",
        "rotoWirePlayerID": "4117",
        "exp": "6",
        "height": "6-3",
        "nbaComID": "1628370",
        "espnHeadshot": "https://a.espncdn.com/i/headshots/nba/players/full/4066262.png",
        "espnID": "4066262",
        "weight": "200",
        "team": "SAC",
        "bRefName": "Malik Monk",
        "espnShortName": "M. Monk",
        "bDay": "2/4/1998",
        "shortName": "M. Monk",
        "longName": "Malik Monk",
        "playerID": "28998641179",
        "stats": {
          "blk": "0.6",
          "fga": "11.2",
          "DefReb": "2.1",
          "ast": "5.4",
          "ftp": "86.7",
          "tptfgp": "41.4",
          "tptfgm": "2.7",
          "trueShootingPercentage": "59.6",
          "stl": "0.6",
          "fgm": "4.9",
          "pts": "14.7",
          "reb": "2.5",
          "fgp": "44.0",
          "effectiveShootingPercentage": "55.9",
          "fta": "2.4",
          "mins": "25.6",
          "gamesPlayed": "34",
          "TOV": "2.1",
          "tptfga": "6.5",
          "OffReb": "0.4",
          "ftm": "2.1"
        }
      },
      {
        "college": "Kentucky",
        "fantasyProsLink": "https://www.fantasypros.com/nba/players/trey-lyles.php",
        "jerseyNum": "41",
        "bRefID": "lylestr01",
        "espnName": "Trey Lyles",
        "yahooLink": "https://sports.yahoo.com/nba/players/5472",
        "sleeperBotID": "1640",
        "fantasyProsPlayerID": "3026",
        "nbaComLink": "https://www.nba.com/player/1626168",
        "nbaComHeadshot": "https://cdn.nba.com/headshots/nba/latest/1040x760/1626168.png",
        "lastGamePlayed": "20240105_TOR@SAC",
        "espnLink": "https://www.espn.com/nba/player/_/id/3136196/trey-lyles",
        "yahooPlayerID": "5472",
        "pos": "PF",
        "teamID": "26",
        "injury": {
          "description": "Jan 8: Lyles (ankle) is questionable for Tuesday's game against the Pistons.",
          "injDate": "20230109",
          "designation": "Day-To-Day"
        },
        "nbaComName": "Trey Lyles",
        "rotoWirePlayerIDFull": "trey-lyles-3738",
        "rotoWirePlayerID": "3738",
        "exp": "8",
        "height": "6-9",
        "nbaComID": "1626168",
        "espnHeadshot": "https://a.espncdn.com/i/headshots/nba/players/full/3136196.png",
        "espnID": "3136196",
        "weight": "234",
        "team": "SAC",
        "bRefName": "Trey Lyles",
        "espnShortName": "T. Lyles",
        "bDay": "11/5/1995",
        "shortName": "T. Lyles",
        "longName": "Trey Lyles",
        "playerID": "28478119129",
        "stats": {
          "blk": "0.4",
          "fga": "5.4",
          "DefReb": "4.0",
          "ast": "1.3",
          "ftp": "62.5",
          "tptfgp": "41.0",
          "tptfgm": "1.6",
          "trueShootingPercentage": "63.8",
          "stl": "0.1",
          "fgm": "2.6",
          "pts": "7.6",
          "reb": "4.9",
          "fgp": "48.2",
          "effectiveShootingPercentage": "63.2",
          "fta": "1.1",
          "mins": "19.6",
          "gamesPlayed": "21",
          "TOV": "0.7",
          "tptfga": "4.0",
          "OffReb": "0.9",
          "ftm": "0.7"
        }
      },
      {
        "college": "Maryland",
        "fantasyProsLink": "https://www.fantasypros.com/nba/players/kevin-huerter.php",
        "jerseyNum": "9",
        "bRefID": "huertke01",
        "espnName": "Kevin Huerter",
        "yahooLink": "https://sports.yahoo.com/nba/players/6030",
        "sleeperBotID": "1941",
        "fantasyProsPlayerID": "3502",
        "nbaComLink": "https://www.nba.com/player/1628989",
        "nbaComHeadshot": "https://cdn.nba.com/headshots/nba/latest/1040x760/1628989.png",
        "lastGamePlayed": "20240107_NO@SAC",
        "espnLink": "https://www.espn.com/nba/player/_/id/4066372/kevin-huerter",
        "yahooPlayerID": "6030",
        "pos": "SG",
        "teamID": "26",
        "injury": {
          "description": "",
          "injDate": "",
          "designation": ""
        },
        "nbaComName": "Kevin Huerter",
        "rotoWirePlayerIDFull": "kevin-huerter-4449",
        "rotoWirePlayerID": "4449",
        "exp": "5",
        "height": "6-7",
        "nbaComID": "1628989",
        "espnHeadshot": "https://a.espncdn.com/i/headshots/nba/players/full/4066372.png",
        "espnID": "4066372",
        "weight": "198",
        "team": "SAC",
        "bRefName": "Kevin Huerter",
        "espnShortName": "K. Huerter",
        "bDay": "8/27/1998",
        "shortName": "K. Huerter",
        "longName": "Kevin Huerter",
        "playerID": "28598696399",
        "stats": {
          "blk": "0.3",
          "fga": "8.7",
          "DefReb": "3.1",
          "ast": "2.5",
          "ftp": "80.6",
          "tptfgp": "34.1",
          "tptfgm": "1.8",
          "trueShootingPercentage": "54.4",
          "stl": "0.6",
          "fgm": "3.7",
          "pts": "9.9",
          "reb": "3.6",
          "fgp": "42.4",
          "effectiveShootingPercentage": "52.7",
          "fta": "0.9",
          "mins": "23.5",
          "gamesPlayed": "34",
          "TOV": "0.6",
          "tptfga": "5.3",
          "OffReb": "0.6",
          "ftm": "0.7"
        }
      },
      {
        "college": "Kentucky",
        "fantasyProsLink": "https://www.fantasypros.com/nba/players/deaaron-fox.php",
        "jerseyNum": "5",
        "bRefID": "foxde01",
        "espnName": "De'Aaron Fox",
        "yahooLink": "https://sports.yahoo.com/nba/players/5767",
        "sleeperBotID": "1872",
        "fantasyProsPlayerID": "3315",
        "nbaComLink": "https://www.nba.com/player/1628368",
        "nbaComHeadshot": "https://cdn.nba.com/headshots/nba/latest/1040x760/1628368.png",
        "lastGamePlayed": "20240107_NO@SAC",
        "espnLink": "https://www.espn.com/nba/player/_/id/4066259/deaaron-fox",
        "yahooPlayerID": "5767",
        "pos": "PG",
        "teamID": "26",
        "injury": {
          "description": "",
          "injDate": "",
          "designation": ""
        },
        "nbaComName": "De'Aaron Fox",
        "rotoWirePlayerIDFull": "deaaron-fox-4116",
        "rotoWirePlayerID": "4116",
        "exp": "6",
        "height": "6-3",
        "nbaComID": "1628368",
        "espnHeadshot": "https://a.espncdn.com/i/headshots/nba/players/full/4066259.png",
        "espnID": "4066259",
        "weight": "185",
        "team": "SAC",
        "bRefName": "De'Aaron Fox",
        "espnShortName": "D. Fox",
        "bDay": "12/20/1997",
        "shortName": "D. Fox",
        "longName": "De'Aaron Fox",
        "playerID": "28828541179",
        "stats": {
          "blk": "0.4",
          "fga": "21.4",
          "DefReb": "3.4",
          "ast": "6.0",
          "ftp": "72.1",
          "tptfgp": "38.7",
          "tptfgm": "3.2",
          "trueShootingPercentage": "57.9",
          "stl": "1.6",
          "fgm": "10.0",
          "pts": "28.3",
          "reb": "4.4",
          "fgp": "46.9",
          "effectiveShootingPercentage": "54.4",
          "fta": "6.9",
          "mins": "35.4",
          "gamesPlayed": "29",
          "TOV": "2.6",
          "tptfga": "8.4",
          "OffReb": "1.0",
          "ftm": "5.0"
        }
      },
      {
        "college": "Oregon",
        "fantasyProsLink": "https://www.fantasypros.com/nba/players/chris-duarte.php",
        "jerseyNum": "3",
        "bRefID": "duartch01",
        "espnName": "Chris Duarte",
        "yahooLink": "https://sports.yahoo.com/nba/players/6555",
        "sleeperBotID": "2261",
        "fantasyProsPlayerID": "5343",
        "nbaComLink": "https://www.nba.com/player/1630537",
        "nbaComHeadshot": "https://cdn.nba.com/headshots/nba/latest/1040x760/1630537.png",
        "lastGamePlayed": "20240107_NO@SAC",
        "espnLink": "https://www.espn.com/nba/player/_/id/4592402/chris-duarte",
        "yahooPlayerID": "6555",
        "pos": "SG",
        "teamID": "26",
        "injury": {
          "description": "",
          "injDate": "",
          "designation": ""
        },
        "nbaComName": "Chris Duarte",
        "rotoWirePlayerIDFull": "https://www.rotowire.com/basketball/player/chris-duarte-5345",
        "rotoWirePlayerID": "5345",
        "exp": "2",
        "height": "6-5",
        "nbaComID": "1630537",
        "espnHeadshot": "https://a.espncdn.com/i/headshots/nba/players/full/4592402.png",
        "espnID": "4592402",
        "weight": "190",
        "team": "SAC",
        "bRefName": "Chris Duarte",
        "espnShortName": "C. Duarte",
        "bDay": "6/13/1997",
        "shortName": "C. Duarte",
        "longName": "Chris Duarte",
        "playerID": "28168576027",
        "stats": {
          "blk": "0.1",
          "fga": "3.8",
          "DefReb": "1.5",
          "ast": "0.9",
          "ftp": "77.3",
          "tptfgp": "31.8",
          "tptfgm": "0.7",
          "trueShootingPercentage": "49.0",
          "stl": "0.6",
          "fgm": "1.4",
          "pts": "4.0",
          "reb": "1.8",
          "fgp": "37.2",
          "effectiveShootingPercentage": "45.9",
          "fta": "0.7",
          "mins": "13.6",
          "gamesPlayed": "32",
          "TOV": "0.6",
          "tptfga": "2.1",
          "OffReb": "0.3",
          "ftm": "0.5"
        }
      },
      {
        "college": "Nevada",
        "fantasyProsLink": "https://www.fantasypros.com/nba/players/javale-mcgee.php",
        "jerseyNum": "00",
        "bRefID": "mcgeeja01",
        "espnName": "JaVale McGee",
        "yahooLink": "https://sports.yahoo.com/nba/players/4480",
        "sleeperBotID": "1466",
        "fantasyProsPlayerID": "2482",
        "nbaComLink": "https://www.nba.com/player/201580",
        "nbaComHeadshot": "https://cdn.nba.com/headshots/nba/latest/1040x760/201580.png",
        "lastGamePlayed": "20240107_NO@SAC",
        "espnLink": "https://www.espn.com/nba/player/_/id/3452/javale-mcgee",
        "yahooPlayerID": "4480",
        "pos": "C",
        "teamID": "26",
        "injury": {
          "description": "",
          "injDate": "",
          "designation": ""
        },
        "nbaComName": "JaVale McGee",
        "rotoWirePlayerIDFull": "javale-mcgee-2930",
        "rotoWirePlayerID": "2930",
        "exp": "15",
        "height": "7-0",
        "nbaComID": "201580",
        "espnHeadshot": "https://a.espncdn.com/i/headshots/nba/players/full/3452.png",
        "espnID": "3452",
        "weight": "270",
        "team": "SAC",
        "bRefName": "JaVale McGee",
        "espnShortName": "J. McGee",
        "bDay": "1/19/1988",
        "shortName": "J. McGee",
        "longName": "JaVale McGee",
        "playerID": "28506619932",
        "stats": {
          "blk": "0.6",
          "fga": "2.9",
          "DefReb": "1.9",
          "ast": "0.5",
          "ftp": "56.2",
          "tptfgp": "0.0",
          "tptfgm": "0.0",
          "trueShootingPercentage": "66.3",
          "stl": "0.2",
          "fgm": "1.9",
          "pts": "4.5",
          "reb": "2.8",
          "fgp": "66.7",
          "effectiveShootingPercentage": "66.7",
          "fta": "1.1",
          "mins": "8.3",
          "gamesPlayed": "30",
          "TOV": "1.0",
          "tptfga": "0.0",
          "OffReb": "0.9",
          "ftm": "0.6"
        }
      },
      {
        "college": "Pepperdine",
        "fantasyProsLink": "https://www.fantasypros.com/nba/players/kessler-edwards.php",
        "jerseyNum": "17",
        "bRefID": "edwarke02",
        "espnName": "Kessler Edwards",
        "yahooLink": "https://sports.yahoo.com/nba/players/6586",
        "sleeperBotID": "2277",
        "fantasyProsPlayerID": "5381",
        "nbaComLink": "https://www.nba.com/player/1630556",
        "nbaComHeadshot": "https://cdn.nba.com/headshots/nba/latest/1040x760/1630556.png",
        "lastGamePlayed": "20240107_NO@SAC",
        "espnLink": "https://www.espn.com/nba/player/_/id/4397693/kessler-edwards",
        "yahooPlayerID": "6586",
        "pos": "SF",
        "teamID": "26",
        "injury": {
          "description": "",
          "injDate": "",
          "designation": ""
        },
        "nbaComName": "Kessler Edwards",
        "rotoWirePlayerIDFull": "kessler-edwards-5419",
        "rotoWirePlayerID": "5419",
        "exp": "2",
        "height": "6-7",
        "nbaComID": "1630556",
        "espnHeadshot": "https://a.espncdn.com/i/headshots/nba/players/full/4397693.png",
        "espnID": "4397693",
        "weight": "203",
        "team": "SAC",
        "bRefName": "Kessler Edwards",
        "espnShortName": "K. Edwards",
        "bDay": "8/9/2000",
        "shortName": "K. Edwards",
        "longName": "Kessler Edwards",
        "playerID": "94784449047",
        "stats": {
          "blk": "0.1",
          "fga": "1.7",
          "DefReb": "0.7",
          "ast": "0.3",
          "ftp": "75.0",
          "tptfgp": "37.5",
          "tptfgm": "0.4",
          "trueShootingPercentage": "55.3",
          "stl": "0.1",
          "fgm": "0.7",
          "pts": "2.0",
          "reb": "0.9",
          "fgp": "42.1",
          "effectiveShootingPercentage": "53.9",
          "fta": "0.2",
          "mins": "5.9",
          "gamesPlayed": "22",
          "TOV": "0.0",
          "tptfga": "1.1",
          "OffReb": "0.2",
          "ftm": "0.1"
        }
      },
      {
        "college": "Iowa",
        "fantasyProsLink": "https://www.fantasypros.com/nba/players/keegan-murray.php",
        "jerseyNum": "13",
        "bRefID": "murrake02",
        "espnName": "Keegan Murray",
        "yahooLink": "https://sports.yahoo.com/nba/players/6694",
        "sleeperBotID": "2456",
        "fantasyProsPlayerID": "5502",
        "nbaComLink": "https://www.nba.com/player/1631099",
        "nbaComHeadshot": "https://cdn.nba.com/headshots/nba/latest/1040x760/1631099.png",
        "lastGamePlayed": "20240107_NO@SAC",
        "espnLink": "https://www.espn.com/nba/player/_/id/4594327/keegan-murray",
        "yahooPlayerID": "6694",
        "pos": "PF",
        "teamID": "26",
        "injury": {
          "description": "",
          "injDate": "",
          "designation": ""
        },
        "nbaComName": "Keegan Murray",
        "rotoWirePlayerIDFull": "keegan-murray-5699",
        "rotoWirePlayerID": "5699",
        "exp": "1",
        "height": "6-8",
        "nbaComID": "1631099",
        "espnHeadshot": "https://a.espncdn.com/i/headshots/nba/players/full/4594327.png",
        "espnID": "4594327",
        "weight": "225",
        "team": "SAC",
        "bRefName": "Keegan Murray",
        "espnShortName": "K. Murray",
        "bDay": "8/19/2000",
        "shortName": "K. Murray",
        "longName": "Keegan Murray",
        "playerID": "94684406527",
        "stats": {
          "blk": "0.4",
          "fga": "12.8",
          "DefReb": "4.1",
          "ast": "1.5",
          "ftp": "82.1",
          "tptfgp": "36.2",
          "tptfgm": "2.4",
          "trueShootingPercentage": "56.4",
          "stl": "1.2",
          "fgm": "5.7",
          "pts": "15.4",
          "reb": "5.5",
          "fgp": "44.7",
          "effectiveShootingPercentage": "54.1",
          "fta": "1.8",
          "mins": "32.9",
          "gamesPlayed": "31",
          "TOV": "0.9",
          "tptfga": "6.7",
          "OffReb": "1.5",
          "ftm": "1.5"
        }
      },
      {
        "college": "Baylor",
        "fantasyProsLink": "https://www.fantasypros.com/nba/players/davion-mitchell.php",
        "jerseyNum": "15",
        "bRefID": "mitchda01",
        "espnName": "Davion Mitchell",
        "yahooLink": "https://sports.yahoo.com/nba/players/6551",
        "sleeperBotID": "2301",
        "fantasyProsPlayerID": "5332",
        "nbaComLink": "https://www.nba.com/player/1630558",
        "nbaComHeadshot": "https://cdn.nba.com/headshots/nba/latest/1040x760/1630558.png",
        "lastGamePlayed": "20240107_NO@SAC",
        "espnLink": "https://www.espn.com/nba/player/_/id/4278053/davion-mitchell",
        "yahooPlayerID": "6551",
        "pos": "PG",
        "teamID": "26",
        "injury": {
          "description": "",
          "injDate": "",
          "designation": ""
        },
        "nbaComName": "Davion Mitchell",
        "rotoWirePlayerIDFull": "davion-mitchell-5354",
        "rotoWirePlayerID": "5354",
        "exp": "2",
        "height": "6-0",
        "nbaComID": "1630558",
        "espnHeadshot": "https://a.espncdn.com/i/headshots/nba/players/full/4278053.png",
        "espnID": "4278053",
        "weight": "202",
        "team": "SAC",
        "bRefName": "Davion Mitchell",
        "espnShortName": "D. Mitchell",
        "bDay": "9/5/1998",
        "shortName": "D. Mitchell",
        "longName": "Davion Mitchell",
        "playerID": "28928649869",
        "stats": {
          "blk": "0.1",
          "fga": "3.9",
          "DefReb": "0.8",
          "ast": "1.9",
          "ftp": "73.3",
          "tptfgp": "24.6",
          "tptfgm": "0.5",
          "trueShootingPercentage": "44.9",
          "stl": "0.2",
          "fgm": "1.4",
          "pts": "3.7",
          "reb": "0.9",
          "fgp": "36.1",
          "effectiveShootingPercentage": "42.6",
          "fta": "0.5",
          "mins": "13.0",
          "gamesPlayed": "28",
          "TOV": "0.6",
          "tptfga": "2.0",
          "OffReb": "0.1",
          "ftm": "0.4"
        }
      },
      {
        "college": "N. Carolina",
        "fantasyProsLink": "https://www.fantasypros.com/nba/players/harrison-barnes.php",
        "jerseyNum": "40",
        "bRefID": "barneha02",
        "espnName": "Harrison Barnes",
        "yahooLink": "https://sports.yahoo.com/nba/players/5013",
        "sleeperBotID": "1092",
        "fantasyProsPlayerID": "2765",
        "nbaComLink": "https://www.nba.com/player/203084",
        "nbaComHeadshot": "https://cdn.nba.com/headshots/nba/latest/1040x760/203084.png",
        "lastGamePlayed": "20240107_NO@SAC",
        "espnLink": "https://www.espn.com/nba/player/_/id/6578/harrison-barnes",
        "yahooPlayerID": "5013",
        "pos": "PF",
        "teamID": "26",
        "injury": {
          "description": "",
          "injDate": "",
          "designation": ""
        },
        "nbaComName": "Harrison Barnes",
        "rotoWirePlayerIDFull": "harrison-barnes-3305",
        "rotoWirePlayerID": "3305",
        "exp": "11",
        "height": "6-8",
        "nbaComID": "203084",
        "espnHeadshot": "https://a.espncdn.com/i/headshots/nba/players/full/6578.png",
        "espnID": "6578",
        "weight": "225",
        "team": "SAC",
        "bRefName": "Harrison Barnes",
        "espnShortName": "H. Barnes",
        "bDay": "5/30/1992",
        "shortName": "H. Barnes",
        "longName": "Harrison Barnes",
        "playerID": "28268959882",
        "stats": {
          "blk": "0.2",
          "fga": "8.0",
          "DefReb": "2.1",
          "ast": "1.3",
          "ftp": "81.7",
          "tptfgp": "41.0",
          "tptfgm": "1.8",
          "trueShootingPercentage": "63.1",
          "stl": "0.7",
          "fgm": "3.8",
          "pts": "11.4",
          "reb": "3.0",
          "fgp": "47.9",
          "effectiveShootingPercentage": "59.3",
          "fta": "2.3",
          "mins": "30.0",
          "gamesPlayed": "35",
          "TOV": "0.7",
          "tptfga": "4.5",
          "OffReb": "0.9",
          "ftm": "1.9"
        }
      },
      {
        "college": "Maryland",
        "fantasyProsLink": "https://www.fantasypros.com/nba/players/alex-len.php",
        "jerseyNum": "25",
        "bRefID": "lenal01",
        "espnName": "Alex Len",
        "yahooLink": "https://sports.yahoo.com/nba/players/5156",
        "sleeperBotID": "1412",
        "fantasyProsPlayerID": "2828",
        "nbaComLink": "https://www.nba.com/player/203458",
        "nbaComHeadshot": "https://cdn.nba.com/headshots/nba/latest/1040x760/203458.png",
        "lastGamePlayed": "20240107_NO@SAC",
        "espnLink": "https://www.espn.com/nba/player/_/id/2596107/alex-len",
        "yahooPlayerID": "5156",
        "pos": "C",
        "teamID": "26",
        "injury": {
          "description": "",
          "injDate": "",
          "designation": ""
        },
        "nbaComName": "Alex Len",
        "rotoWirePlayerIDFull": "alex-len-3436",
        "rotoWirePlayerID": "3436",
        "exp": "10",
        "height": "7-0",
        "nbaComID": "203458",
        "espnHeadshot": "https://a.espncdn.com/i/headshots/nba/players/full/2596107.png",
        "espnID": "2596107",
        "weight": "250",
        "team": "SAC",
        "bRefName": "Alex Len",
        "espnShortName": "A. Len",
        "bDay": "6/16/1993",
        "shortName": "A. Len",
        "longName": "Alex Len",
        "playerID": "28768735349",
        "stats": {
          "blk": "0.5",
          "fga": "1.3",
          "DefReb": "1.9",
          "ast": "1.5",
          "ftp": "44.4",
          "tptfgp": "0.0",
          "tptfgm": "0.0",
          "trueShootingPercentage": "55.6",
          "stl": "0.2",
          "fgm": "0.7",
          "pts": "1.8",
          "reb": "3.1",
          "fgp": "57.1",
          "effectiveShootingPercentage": "57.1",
          "fta": "0.8",
          "mins": "8.4",
          "gamesPlayed": "11",
          "TOV": "0.5",
          "tptfga": "0.1",
          "OffReb": "1.2",
          "ftm": "0.4"
        }
      },
      {
        "college": "Gonzaga",
        "fantasyProsLink": "https://www.fantasypros.com/nba/players/domantas-sabonis.php",
        "jerseyNum": "10",
        "bRefID": "sabondo01",
        "espnName": "Domantas Sabonis",
        "yahooLink": "https://sports.yahoo.com/nba/players/5642",
        "sleeperBotID": "1739",
        "fantasyProsPlayerID": "3176",
        "nbaComLink": "https://www.nba.com/player/1627734",
        "nbaComHeadshot": "https://cdn.nba.com/headshots/nba/latest/1040x760/1627734.png",
        "lastGamePlayed": "20240107_NO@SAC",
        "espnLink": "https://www.espn.com/nba/player/_/id/3155942/domantas-sabonis",
        "yahooPlayerID": "5642",
        "pos": "C",
        "teamID": "26",
        "injury": {
          "description": "",
          "injDate": "",
          "designation": ""
        },
        "nbaComName": "Domantas Sabonis",
        "rotoWirePlayerIDFull": "domantas-sabonis-3865",
        "rotoWirePlayerID": "3865",
        "exp": "7",
        "height": "6-10",
        "nbaComID": "1627734",
        "espnHeadshot": "https://a.espncdn.com/i/headshots/nba/players/full/3155942.png",
        "espnID": "3155942",
        "weight": "240",
        "team": "SAC",
        "bRefName": "Domantas Sabonis",
        "espnShortName": "D. Sabonis",
        "bDay": "5/3/1996",
        "shortName": "D. Sabonis",
        "longName": "Domantas Sabonis",
        "playerID": "28118309129",
        "stats": {
          "blk": "0.5",
          "fga": "13.2",
          "DefReb": "9.5",
          "ast": "7.6",
          "ftp": "65.4",
          "tptfgp": "37.5",
          "tptfgm": "0.4",
          "trueShootingPercentage": "63.0",
          "stl": "0.8",
          "fgm": "7.9",
          "pts": "19.7",
          "reb": "12.8",
          "fgp": "59.4",
          "effectiveShootingPercentage": "61.0",
          "fta": "5.4",
          "mins": "35.0",
          "gamesPlayed": "35",
          "TOV": "3.3",
          "tptfga": "1.1",
          "OffReb": "3.4",
          "ftm": "3.5"
        }
      },
    ]
  }
}

const Roster: React.FC<RosterProps> = ({ teamData }) => {
  return (
    <div className="flex justify-center pb-8">
      <Grid
        container
        columnSpacing={4}
        padding={4}
        className="gap-y-6 sm:gap-y-8 md:gap-y-4 lg:gap-y-1 max-w-screen-2xl"
      >
        <Grid item xs={12} md={2.6}>
          <div className="flex flex-col gap-4 md:gap-0">
            <TeamExInfo teamData={teamData} />
            <ToolsWidget />
          </div>
        </Grid>
        <Grid item xs={12} md={9.4}>
          <RosterWidget rosterData={RosterData} />
        </Grid>
      </Grid>
    </div>
  );
};

export default Roster;
