import React from 'react'
import { Button } from "@/components/ui/button"
import DataTable  from '@/pages/PlayerDash/Overview/components/games/DataTable'; 
import { PlayerGameStats } from '@/types/Dash/PlayerDash';
import {columns} from '@/pages/PlayerDash/Overview/components/games/columns'

interface GamePerformanceProps {
  changeTabToMatches: () => void;
}

const GamePerformance: React.FC<GamePerformanceProps> = ({ changeTabToMatches }) => {
  const gameData: PlayerGameStats[] = [
    // Example data
    {
      blk: 0,
      OffReb: 3,
      ftp: 100,
      DefReb: 5,
      plusMinus: "+12",
      stl: 2,
      pts: 30,
      tech: 1,
      team: "CHI",
      TOV: 88,
      fga: 22,
      ast: 5,
      tptfgp: 36.4,
      teamAbv: "CHI",
      mins: 40,
      fgm: 10,
      fgp: 45.5,
      reb: 8,
      teamID: "5",
      tptfgm: 4,
      fta: 4,
      tptfga: 11,
      longName: "Zach LaVine",
      PF: 1,
      playerID: "28228405031",
      ftm: 4,
      gameID: "20240108_CHI@CHA",
      fantasyPoints: 50.0,
    },
    {
      blk: 0,
      OffReb: 3,
      ftp: 100,
      DefReb: 5,
      plusMinus: "-12",
      stl: 2,
      pts: 30,
      tech: 1,
      team: "CHI",
      TOV: 88,
      fga: 22,
      ast: 5,
      tptfgp: 36.4,
      teamAbv: "CHI",
      mins: 40,
      fgm: 10,
      fgp: 45.5,
      reb: 8,
      teamID: "5",
      tptfgm: 4,
      fta: 4,
      tptfga: 11,
      longName: "Zach LaVine",
      PF: 1,
      playerID: "28228405031",
      ftm: 4,
      gameID: "20240108_CHI@CHA",
      fantasyPoints: 50.0,
    },
    {
      blk: 0,
      OffReb: 3,
      ftp: 100,
      DefReb: 5,
      plusMinus: "-12",
      stl: 2,
      pts: 30,
      tech: 1,
      team: "CHI",
      TOV: 88,
      fga: 22,
      ast: 5,
      tptfgp: 36.4,
      teamAbv: "CHI",
      mins: 40,
      fgm: 10,
      fgp: 45.5,
      reb: 8,
      teamID: "5",
      tptfgm: 4,
      fta: 4,
      tptfga: 11,
      longName: "Zach LaVine",
      PF: 1,
      playerID: "28228405031",
      ftm: 4,
      gameID: "20240108_CHI@CHA",
      fantasyPoints: 50.0,
    },
    {
      blk: 0,
      OffReb: 3,
      ftp: 100,
      DefReb: 5,
      plusMinus: "-12",
      stl: 2,
      pts: 30,
      tech: 1,
      team: "CHI",
      TOV: 88,
      fga: 22,
      ast: 5,
      tptfgp: 36.4,
      teamAbv: "CHI",
      mins: 40,
      fgm: 10,
      fgp: 45.5,
      reb: 8,
      teamID: "5",
      tptfgm: 4,
      fta: 4,
      tptfga: 11,
      longName: "Zach LaVine",
      PF: 1,
      playerID: "28228405031",
      ftm: 4,
      gameID: "20240108_CHI@CHA",
      fantasyPoints: 50.0,
    },
    {
      blk: 0,
      OffReb: 3,
      ftp: 100,
      DefReb: 5,
      plusMinus: "-12",
      stl: 2,
      pts: 30,
      tech: 1,
      team: "CHI",
      TOV: 88,
      fga: 22,
      ast: 5,
      tptfgp: 36.4,
      teamAbv: "CHI",
      mins: 40,
      fgm: 10,
      fgp: 45.5,
      reb: 8,
      teamID: "5",
      tptfgm: 4,
      fta: 4,
      tptfga: 11,
      longName: "Zach LaVine",
      PF: 1,
      playerID: "28228405031",
      ftm: 4,
      gameID: "20240108_CHI@CHA",
      fantasyPoints: 50.0,
    },
    // Add more game data objects here
  ];

  return (
    <div className=" flex flex-col gap-3">
      <DataTable data={gameData} columns={columns}/>
      <Button  onClick={changeTabToMatches} variant="outline" className="self-center w-3/4 bg-transparent text-gray-100 border-white hover:border-2 mb-3">
        View All Matches
      </Button>
    </div>
  );
}

export default GamePerformance;